### ISSUE TITLE
Add Scene Manager

### ISSUE THREAD

**Issue by RedWheeler** [redwheelergames/game-engine#2]
Users need to be able to easily switch between scenes. This feature is essential as this capability is needed for changing levels, UIs, and memory optimization. This issue requires #1 to be completed first, as there currently is no way to represent multiple scenes in the game engine. Once #1 is addressed, some state changing mechanism needs to be added to `Game.java`. This should allow game objects' components to change the scene when a certain condition is met. For example, a main menu can be implemented by creating a scene that contains UI elements and controls. A button game object and component can be created in this scene that waits to be clicked. When this happens this component should be able to tell the Game object to change to the `main` scene.

**Comment by RedWheeler** [comment]
Closed by #3

**Comment by pyvelepor** [comment]
Found some related issues while updating AotB to use the new scene manager class:

1. Adding game objects to the scene was deferred, but adding the references to the requested groups was not.
2. When a new scene would be loaded, the old list of groups wasn't being cleared.
3. Newly instantiated game objects call `SceneManager.getGroup` during `Scene.load`. This leads to an error being raised because these objects are not in the scene yet. Adding objects to the scene is deferred until `Scene.load` is completed.

@RedWheeler Because we might encounter other issues related to `SceneManager`, could we reopen this issue?

**Comment by RedWheeler** [comment]
> 
> 
> Found some related issues while updating AotB to use the new scene manager class:
> 
>     1. Adding game objects to the scene was deferred, but adding the references to the requested groups was not.
> 
>     2. When a new scene would be loaded, the old list of groups wasn't being cleared.
> 
>     3. Newly instantiated game objects call `SceneManager.getGroup` during `Scene.load`. This leads to an error being raised because these objects are not in the scene yet. Adding objects to the scene is deferred until `Scene.load` is completed.
> 
> 
> @RedWheeler Because we might encounter other issues related to `SceneManager`, could we reopen this issue?

@pyvelepor reopened. In regard to 3 - Could we implement this through a `start` method on `Component`? After calling `load` within `SceneManager.updateGameObjects` we could just iterate through all of the newly added GameObjects and call `start` on each of their components. 

If we do this I think we will have to be careful to not call `start` on Components that are remaining in the scene from #16. It might make sense to change `Scene.load` to return a list of GameObjects to be added that way we can be sure which GameObjects and Component are new vs. the ones that are sticking around from the last scene.
